language: objective-c
osx_image: xcode7.1
xcode_workspace: BrainCore.xcworkspace
xcode_scheme: BrainCore.OSX
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.9.4/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage bootstrap --verbose
